apiVersion: v1
kind: Service
metadata:
  name: bizcord-backend
  namespace: {{ include "bizcord.namespace" . }}
  labels:
    {{- include "bizcord.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bizcord-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
