apiVersion: v1
kind: Secret
metadata:
  name: bizcord-minio-secret
  namespace: {{ include "bizcord.namespace" . }}
  labels:
    {{- include "bizcord.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.secrets.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.secrets.rootPassword | quote }}
