apiVersion: v1
kind: Secret
metadata:
  name: bizcord-postgres-secret
  namespace: {{ include "bizcord.namespace" . }}
  labels:
    {{- include "bizcord.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.secrets.password | quote }}
