apiVersion: v1
kind: Service
metadata:
  name: bizcord-frontend
  namespace: {{ include "bizcord.namespace" . }}
  labels:
    {{- include "bizcord.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: bizcord-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
